add_newline = true
format = """
$directory\
$git_branch\
$git_status\
$git_state\
$aws\
$character\
"""
palette = "catppuccin_mocha"
command_timeout = 1000
# move the rest of the prompt to the right
right_format = """$all"""

[git_branch]
format =  '[$symbol($branch(:$remote_branch) )]($style)'
style = 'bold bright-black'

[git_status]
style = 'bold bright-black'

[git_state]
format = '[\($state( $progress_current of $progress_total)\) ]($style)'
style = 'bold bright-black'

[aws]
format = '[($symbol$profile )]($style)'
disabled = false
style = 'bold bright-black'
symbol = " "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#c5c8c6"
format = '[ $time ]($style)'

[golang]
disabled = true

[nodejs]
disabled = true

[terraform]
disabled = true

